// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RolesInitParameters struct {

	// (String) DB Where the user is registered
	DB *string `json:"db,omitempty" tf:"db"`

	// (String)
	Role *string `json:"role,omitempty" tf:"role"`
}

type RolesObservation struct {

	// (String) DB Where the user is registered
	DB *string `json:"db,omitempty" tf:"db,omitempty"`

	// (String)
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RolesParameters struct {

	// (String) DB Where the user is registered
	// +kubebuilder:validation:Optional
	DB *string `json:"db" tf:"db"`

	// (String)
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role"`
}

type UserInitParameters struct {

	// (String) DB Where the user is registered
	// DB Where the user is registered
	DB *string `json:"db,omitempty" tf:"db,omitempty"`

	// (Set of Object) Set of roles that the user has (see below for nested schema)
	// Set of roles that the user has
	Roles []RolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) Name of user
	// Name of user
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type UserObservation struct {

	// (String) DB Where the user is registered
	// DB Where the user is registered
	DB *string `json:"db,omitempty" tf:"db,omitempty"`

	// (String) Placeholder identifier attribute
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Set of Object) Set of roles that the user has (see below for nested schema)
	// Set of roles that the user has
	Roles []RolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) Name of user
	// Name of user
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type UserParameters struct {

	// (String) DB Where the user is registered
	// DB Where the user is registered
	// +kubebuilder:validation:Optional
	DB *string `json:"db,omitempty" tf:"db,omitempty"`

	// (String, Sensitive) Password of user, cannot be changed once set
	// Password of user, cannot be changed once set
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Set of Object) Set of roles that the user has (see below for nested schema)
	// Set of roles that the user has
	// +kubebuilder:validation:Optional
	Roles []RolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) Name of user
	// Name of user
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// User is the Schema for the Users API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mongodb-users}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.db) || (has(self.initProvider) && has(self.initProvider.db))",message="spec.forProvider.db is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.user) || (has(self.initProvider) && has(self.initProvider.user))",message="spec.forProvider.user is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
