name: mcwhitak/mongodb-users
resources:
    mongodb-users_user:
        subCategory: ""
        name: mongodb-users_user
        title: mongodb-users_user Resource - mongodb-users
        examples:
            - name: user1
              manifest: |-
                {
                  "db": "test",
                  "password": "abc123",
                  "roles": [
                    {
                      "db": "test",
                      "role": "readWrite"
                    }
                  ],
                  "user": "user1"
                }
        argumentDocs:
            db: (String) DB Where the user is registered
            id: (String) Placeholder identifier attribute
            last_updated: (String) Timestamp of the last Terraform update of the order.
            password: (String, Sensitive) Password of user, cannot be changed once set
            role: (String)
            roles: (Set of Object) Set of roles that the user has (see below for nested schema)
            user: (String) Name of user
        importStatements:
            - terraform import mongodb-users_user.user1 test.user1
