apiVersion: user.pelotech/v1alpha1
kind: User
metadata:
  name: hello-crossplane
spec:
  forProvider:
    db: test
    passwordSecretRef:
      key: password
      name: user-creds
      namespace: default
    roles:
    - db: test
      role: readWrite
    user: user1
  providerConfigRef:
    name: default
